In [ ]:
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1=pd.Series(mylist)
ser2=pd.Series(myarr)
ser3=pd.Series(mydict)

print(ser3.head())

a    0
b    1
c    2
e    3
d    4
dtype: int64


In [ ]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df=ser.to_frame()
print(df.head())

   0
a  0
b  1
c  2
e  3
d  4


In [ ]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1=pd.Series(mylist)
ser2=pd.Series(myarr)
df=pd.concat([ser1,ser2],axis=0)
df=pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())


  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


In [ ]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = 'latin_letters'
print(ser.head())

0    a
1    b
2    c
3    e
4    d
Name: latin_letters, dtype: object


In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

res = ser1[~np.isin(ser1, ser2)]
print(res)

0    1
1    2
2    3
dtype: int64


In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = pd.Series(np.union1d(ser1, ser2))
intersect = pd.Series(np.intersect1d(ser1, ser2))
notcommonseries = union[~union.isin(intersect)]
print(notcommonseries)

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64


In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))

result = np.percentile(ser, q=[0, 25, 50, 75, 100])
print("\nMinimum, 25th percentile, median, 75th, and maximum of a given series:")
print(result)


Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 1.48683553  6.48808456 10.26005679 12.49496658 24.90588727]


In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

print(ser.value_counts())

f    8
g    4
d    4
e    4
a    3
c    3
h    2
b    2
dtype: int64


In [ ]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

print("Топ 2:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = "Прочее"
print("\n")
print(ser)

Топ 2: 3    5
2    3
4    3
1    1
dtype: int64


0     Прочее
1          2
2          3
3     Прочее
4          3
5          3
6          2
7          3
8     Прочее
9          2
10    Прочее
11         3
dtype: object


In [ ]:
ser = pd.Series(np.random.random(20))

print(ser.head())
print("\n")
pd.qcut(ser,q=[0,.10,.20,.30,.40,.50,.60,.70,.80,.90,1],labels=['1','2','3','4','5','6','7','8','9','10']).head()

0    0.153801
1    0.071990
2    0.720349
3    0.957589
4    0.538270
dtype: float64




0     2
1     1
2     9
3    10
4     7
dtype: category
Categories (10, object): ['1' < '2' < '3' < '4' ... '7' < '8' < '9' < '10']

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 35))

df=pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  3  9  7  9  4
1  8  5  6  5  8
2  4  7  5  7  8
3  7  6  1  5  8
4  4  7  7  7  9
5  4  2  6  8  6
6  6  4  7  3  4


In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))

res= ser[ser % 3 == 0].index
print(res)

Int64Index([0, 1, 6], dtype='int64')


In [ ]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

res = ser.take(pos)
print(res)

0     a
4     e
8     i
14    o
20    u
dtype: object


In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

res_vertical = ser1.append(ser2)
res_horizontal = pd.concat([ser1, ser2], axis=1)

print(res_vertical)
print("\n")
print(res_horizontal)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object


   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


<ipython-input-45-bf1f73fef59b>:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_vertical = ser1.append(ser2)


In [ ]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

[np.where(i==ser1)[0].tolist()[0] for i in ser2]
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [ ]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean((truth-pred)**2)

0.22096596139845848

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

newser=ser.map(lambda x: x.title())
print(newser)

0     How
1      To
2    Kick
3    Ass?
dtype: object


In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

res = ser.map(lambda calc: len(calc))
print(res)

0    3
1    2
2    4
3    4
dtype: int64


In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print(ser.diff())

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64


In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

res = pd.to_datetime(ser)
print(res)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil.parser import parse
res = ser.map(lambda x: parse(x))
print("Day of month:")
print(res.dt.day.tolist())
print("Day of year:")
print(res.dt.dayofyear.tolist())
print("Week number:")
print(res.dt.weekofyear.tolist())
print("Day of week:")
print(list(res.dt.day_name()))

Day of month:
[1, 2, 3, 4, 5, 6]
Day of year:
[1, 33, 63, 94, 125, 157]
Week number:
[53, 5, 9, 14, 19, 23]
Day of week:
['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


<ipython-input-79-d2f430d34987>:10: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  print(res.dt.weekofyear.tolist())


In [ ]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

print(pd.to_datetime(ser).apply(lambda x: x.replace(day=4)))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


In [ ]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

from collections import Counter

mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiouаоиеёэыуюя')]) >= 2)
res = ser[mask]
print(res)

0     Apple
1    Orange
4     Money
dtype: object


In [ ]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

import re
mask = emails.map(lambda x: bool(re.match(pattern, x)))
res = emails[mask]
print(res)

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
print("\n")

weights.groupby(fruit).mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'apple', 'banana', 'carrot', 'carrot', 'carrot', 'apple', 'carrot', 'carrot', 'banana']




apple     4.5
banana    6.5
carrot    5.5
dtype: float64

In [ ]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

res = sum((p-q)**2)**0.5
print(res)

18.16590212458495


In [ ]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7])

In [ ]:
my_str = 'dbc deb abed gade'

ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
least_freq = freq.dropna().index[-1]
''.join(ser.replace(' ', least_freq))

'dbcgdebgabedggade'

In [ ]:
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    1
2000-01-08    2
2000-01-15    9
2000-01-22    7
2000-01-29    7
2000-02-05    3
2000-02-12    1
2000-02-19    5
2000-02-26    9
2000-03-04    3
Freq: W-SAT, dtype: int64

In [ ]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

print("\n")
ser=ser.resample('D').ffill()  # fill with previous value
ser=ser.resample('D').bfill()  # fill with previous value
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64


In [ ]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorr = [ser.autocorr(lag=i).round(2) for i in range(20)]
print(autocorr)
print('Наиб. корреляция: ', np.argmax(np.abs(autocorr[1:]))+1)

[1.0, -0.08, -0.1, 0.37, 0.06, -0.15, 0.28, -0.14, -0.2, 0.29, -0.14, -0.5, 0.06, -0.14, -0.09, 0.66, -0.78, 0.74, -1.0, nan]
Наиб. корреляция:  19


/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2845: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2704: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()
print(df2.head())

        crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  0.871  6.122  97.3  1.6180  5.0  403.0   
200  0.01778  95.0   1.47   0.0  0.403  7.135  13.9  7.6534  3.0  402.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})
print(df.head())

      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High  


In [ ]:
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.shape)

print(df.dtypes)

print(df.dtypes.value_counts())

df_stats = df.describe()

df_arr = df.values

df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']])
row, col = np.where(df.values == np.max(df.Price))
print(df.iat[row[0], col[0]])
print(df.iloc[row[0], col[0]])

     Manufacturer Model     Type
58  Mercedes-Benz  300E  Midsize
61.9


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

df=df.rename(columns = {'Type':'CarType'})
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')
Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.isnull().values.any()

True

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

n_missings_each_col = df.apply(lambda x: x.isnull().sum())
print(n_missings_each_col.argmax())
print(df.apply(lambda x: x.isnull().sum()).idxmax())

23
Luggage.room


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000      18.80
1  29.200000      38.70
2  25.900000      32.30
3  17.118605      44.60
4  17.118605      19.15


In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

pandas.core.frame.DataFrame

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

df[list('cbade')]
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]
df1 = switch_columns(df, 'a', 'c')
df[sorted(df.columns)]

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

In [ ]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

df.round(4)
df.apply(lambda x: '%.4f' % x, axis=1)
pd.set_option('display.float_format', lambda x: '%.4f' % x)
pd.options.display.float_format = '{:.4f}'.format
print(df)
pd.options.display.float_format = None

   random
0  0.0000
1  0.0000
2  0.0000
3  0.0011


In [ ]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

out = df.style.format({'random': '{0:.2%}'.format,})
out

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df_out=df[['Manufacturer', 'Model', 'Type', 'Min.Price', 'Max.Price']] = df[['Manufacturer', 'Model', 'Type', 'Min.Price', 'Max.Price']].fillna('missing')
print(df_out.head())
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

  Manufacturer    Model     Type Min.Price Max.Price
0        Acura  Integra    Small      12.9      18.8
1      missing   Legend  Midsize      29.2      38.7
2         Audi       90  Compact      25.9      32.3
3         Audi      100  Midsize   missing      44.6
4          BMW     535i  Midsize   missing   missing
True


In [ ]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

print(df)
print("\n")
print(df['a'].argsort())
n = 5
print("\n")
df['a'].argsort()[::-1][n]

    a   b   c
0   4  27   1
1  14   2  11
2  13   8  15
3  15   3  17
4  24   5   9
5   6   4  17
6   8  29  18
7   8  12  21
8  22  27   8
9  20  26   2


0    0
1    5
2    6
3    7
4    2
5    1
6    3
7    9
8    8
9    4
Name: a, dtype: int64




1

In [ ]:
ser = pd.Series(np.random.randint(1, 100, 15))

print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
ser_mean = np.mean(ser.values).round()
greater_than_mean_arr = ser.where(ser > ser_mean).dropna().sort_values()
row_second_largest_num = greater_than_mean_arr.index[1]
row_second_largest_num

ser:  [75, 35, 69, 45, 61, 68, 79, 22, 40, 93, 64, 97, 14, 99, 47] mean:  61


5

In [ ]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

rowsums = df.apply(np.sum, axis=1).sort_values()
print(rowsums)
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
print(last_two_rows)

11     88
3      95
4      95
2      96
10     96
12     98
0     101
5     101
1     103
9     106
13    109
8     113
6     115
14    115
7     117
dtype: int64
     0   1   2   3
13  20  36  29  24
14  32  18  37  28


In [ ]:
ser = pd.Series(np.logspace(-2, 2, 30))

print(ser)
print("\n")
low_perc = ser.quantile(q=0.05)
print(low_perc)
high_perc = ser.quantile(q=0.95)
print(high_perc)
ser.where(ser > low_perc, other=low_perc, inplace=True)
ser.where(ser < high_perc, other=high_perc, inplace=True)
print("\n")
print(ser)

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64


0.016049294076965887
63.87667222018393


0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
5      0.048939
6      0.067234
7      0.092367
8      0.126896
9      0.174333
10     0.239503
11     0.329034
12     0.452035
13     0.621017
14     0.853168
15     1.172102
16     1.610262
17     2.212216
18     3.039195
19     4.175319
20     5.736153
21     7.880463
22    10.826367
23    14.873521
24    20.433597
25    28.072162
26    38.566204


In [ ]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

print(df)
print("\n")
arr = df[df > 0].values.flatten()
pos_arr = arr[~np.isnan(arr)]
n = int(np.floor(pos_arr.shape[0]**.5))
top_indexes = np.argsort(pos_arr)[::-1]
output = np.take(pos_arr, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0  24   9  11  10   5 -17 -14 -16   7  19
1  28  27 -11 -10 -19  33  22   3  -4 -18
2  42  22   5  34  37 -18  36  42 -17  23
3  40  37  44  28  28  29  46  24  21  -8
4  -8  24  21  42  14 -20  27  41  32  42
5  23 -10  18  44  -4  35  -3   1  32  13
6 -13  41 -10  14  36   9  12 -10  30  11
7  21  30  35  45  16   3  38  -7  43   8
8 -10  -8  -5  40 -17  12  46  24  33  18
9  22  12  16  40  -9  11  48  44 -10  13


[[24. 11. 19. 28. 27. 33. 22. 42.]
 [22. 34. 37. 36. 42. 23. 40. 37.]
 [44. 28. 28. 29. 46. 24. 21. 24.]
 [21. 42. 14. 27. 41. 32. 42. 23.]
 [18. 44. 35. 32. 13. 41. 14. 36.]
 [12. 30. 11. 21. 30. 35. 45. 16.]
 [38. 43. 40. 12. 46. 24. 33. 18.]
 [22. 12. 16. 40. 11. 48. 44. 13.]]


In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

print(df)
print("\n")
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df
print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

print(df)
print("\n")
df.iloc[::-1]

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24




0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

print(df)
print("\n")
one_hot = pd.get_dummies(df["a"])
print(one_hot)
print("\n")
pd.concat([one_hot, df[["b","c","d","e"]]],axis=1)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


   0   5   10  15  20
0   1   0   0   0   0
1   0   1   0   0   0
2   0   0   1   0   0
3   0   0   0   1   0
4   0   0   0   0   1




0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

print(df)
print("\n")
row_high_num = df.sum(axis=0).argmax()
print(row_high_num)

    0   1   2   3
0  58  76  93  55
1   1  24  88  62
2  35  80  36  59
3  99  79  19  28
4   4   6  59  90
5  73  61  73  66
6  53   8  62  70
7  86   1  85  93
8  49  15  40  84
9  59  55   2   8


3


In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

print(df)
print("\n")
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(df)
distances, indices = nbrs.kneighbors(df)
df.insert(4,"nearest row",df.index[indices[:,1]],True)
df.insert(5,"distances", distances[:,1],True)
print(df.index[indices[:,1]])

    p   q   r   s
a  65  31  60  83
b  98  49  41   9
c   7  30  93  46
d  29  99  61  99
e  17  34  35  74
f  55  38  31  49
g  81  20  52  87
h  28  55  47   6
i  73  21  17  27
j   4  25   2  14


Index(['g', 'i', 'e', 'e', 'f', 'i', 'a', 'f', 'f', 'h'], dtype='object')


In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

print(df)
print("\n")
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Макс. корреляция каждого столбца: ', np.round(max_corr.tolist(), 2))

    p   q   r   s   t   u   v   w   x   y
a  64  43  11  65  87  87  16  66  19   5
b  40  76  32   5  67  86   9  87   2  87
c  83  99  11  88  12   2  16  20   6   4
d  61  41  97   4   1  44  21  52  80  25
e   7  21  47  65  24  41  46  27  96  68
f  75  26  20  26  91  33  69  51  44  39
g   6  35  39  80  16  59  31  51  63  42
h  45  16  78  78  59   6  98   7   8  87


Макс. корреляция каждого столбца:  [0.56 0.71 0.45 0.66 0.49 0.9  0.71 0.9  0.52 0.56]


In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

print(df)
print("\n")
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)
print(min_by_max)

    0   1   2   3   4   5   6   7   8   9
0  35  29  67  38  56  36  29  86  60  76
1  80   4  99  29  92  85  73  81  29   8
2  51  62  29  77  97  75  62  26  54  11
3  37  69  32  52   3  66  35  28  59   5
4  16   9  43  47  89  41  64  55   2  74
5  63  78  69  77  39  70  80  38  68  45
6  60  49  79  21  35  58   8  11  99  67
7  73  46  21  40  16  34  51  51   4   4


0    0.337209
1    0.040404
2    0.113402
3    0.043478
4    0.022472
5    0.475000
6    0.080808
7    0.054795
dtype: float64


In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

print(df)
print("\n")
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4   5   6   7   8   9
0  20  42  79  53  25  60  20  13  89  47
1  75   5  85  59   5  79  81  45  69  75
2  30  83  80  80   5  75  37  11  69  72
3  29  52  24  29  23  21  79  73   6  67
4  75  46  80  82  91  97  86  16  18  95
5  21  70  58   4  75  81   4  38  10  11
6  96  65  41  93  40  14  71  38  22  16
7  19  59  26  40  75  37  71  83   8  14


    0   1   2   3   4   5   6   7   8   9  penultimate
0  20  42  79  53  25  60  20  13  89  47           79
1  75   5  85  59   5  79  81  45  69  75           81
2  30  83  80  80   5  75  37  11  69  72           80
3  29  52  24  29  23  21  79  73   6  67           73
4  75  46  80  82  91  97  86  16  18  95           95
5  21  70  58   4  75  81   4  38  10  11           75
6  96  65  41  93  40  14  71  38  22  16           93
7  19  59  26  40  75  37  71  83   8  14           75


In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

print(df)
print("\n")
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('№1\n',out1)
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('№2\n', out2)

    0   1   2   3   4   5   6   7   8   9
0  29  17   2  65  76  30  88   4  78  57
1  47  75  34  37  92  64  44  81  20  38
2  93  62  93  82  61   4  49  58   2  64
3  84  64   8  70  83  94  30  30  65   8
4  67  98  88  26  34  39  98  96  26  86
5  67  52  13   8  14  89  11  70  70  19
6  67  85  19  80  26  68  87  54  92  36
7  28   9  14  98  31  17  44  40  54  39


№1
       0     1     2     3     4     5     6     7     8     9
0 -1.31 -1.31 -0.88  0.22  0.81 -0.62  1.02 -1.71  0.86  0.54
1 -0.56  0.55  0.00 -0.68  1.35  0.40 -0.40  0.92 -0.98 -0.21
2  1.38  0.14  1.63  0.76  0.30 -1.41 -0.24  0.13 -1.55  0.82
3  1.00  0.20 -0.72  0.38  1.05  1.31 -0.85 -0.82  0.45 -1.41
4  0.28  1.29  1.50 -1.03 -0.61 -0.35  1.34  1.43 -0.79  1.70
5  0.28 -0.18 -0.58 -1.61 -1.29  1.16 -1.46  0.54  0.61 -0.97
6  0.28  0.88 -0.41  0.70 -0.88  0.52  0.98 -0.00  1.30 -0.29
7 -1.35 -1.57 -0.55  1.27 -0.72 -1.01 -0.40 -0.48  0.10 -0.17
№2
       0     1     2     3     4     5     6     7     

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

print(df)
print("\n")
print([df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]])

    0   1   2   3   4   5   6   7   8   9
0   8  88  24  35  18  73  70  95  86  30
1  64  85  11  34  16  92  89  47  86  49
2  37  43  95  50   7  13  39  59  85  45
3  64  29  63  86  54  70  69  94  32  88
4  80  99   2  77  48  36  56  15  69  67
5  78  73  71  16  33  18  35   4  80  11
6  35  72  62  38  20  21   2  70  13   5
7  37  29  65  94   3   8  17  80  27  68


[0.64, -0.17, -0.11, -0.4, 0.28, 0.18, 0.41]


In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

print(df)
print("\n")
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
print(df)

    0   1   2   3   4   5   6   7   8   9
0  86  21  20   4  31  76  10  27  77  10
1  83  54  59  51  29  74   9  75  50  24
2  77  18  63  12  32   4  79  36  68  52
3  26  94  31  69  18  61  54  91  90   6
4  80  76   2  76   8  55  40  41   7  95
5  92  87  21  92  97  86  65  42  44  45
6  48  58  36  88  77  84  25  22  13  19
7  58  76  74  89  78   1  96  82  53  69
8  28  37  81  16   7  73  73  59  39  12
9  16  68  37  22  17  47  86  80  18  63


    0   1   2   3   4   5   6   7   8   9
0   0  21  20   4  31  76  10  27  77   0
1  83   0  59  51  29  74   9  75   0  24
2  77  18   0  12  32   4  79   0  68  52
3  26  94  31   0  18  61   0  91  90   6
4  80  76   2  76   0   0  40  41   7  95
5  92  87  21  92   0   0  65  42  44  45
6  48  58  36   0  77  84   0  22  13  19
7  58  76   0  89  78   1  96   0  53  69
8  28   0  81  16   7  73  73  59   0  12
9   0  68  37  22  17  47  86  80  18   0


In [ ]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

print(df)
print("\n")
df_grouped = df.groupby(['col1'])
df_grouped.get_group('apple')
for i, dff in df_grouped:
    if i == 'apple':
        print(dff)

     col1      col2  col3
0   apple  0.680255     6
1  banana  0.982868     0
2  orange  0.716412     8
3   apple  0.231484     7
4  banana  0.721375     9
5  orange  0.667847     2
6   apple  0.952179     6
7  banana  0.255133     2
8  orange  0.521159     5


    col1      col2  col3
0  apple  0.680255     6
3  apple  0.231484     7
6  apple  0.952179     6


<ipython-input-11-8b40a11c707d>:9: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for i, dff in df_grouped:


In [ ]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)
print("\n")
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]


    fruit     taste  price
0   apple  0.563780      3
1  banana  0.750407      0
2  orange  0.003166      9
3   apple  0.667083      5
4  banana  0.606183      1
5  orange  0.046580      6
6   apple  0.062110     12
7  banana  0.229510     14
8  orange  0.115393     12




0.6061826362439088

In [ ]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)
print("\n")
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit    rating  price
0   apple  0.503180     10
1  banana  0.355223      5
2  orange  0.893262     13
3   apple  0.030247      9
4  banana  0.410460      0
5  orange  0.990510      1
6   apple  0.909350     14
7  banana  0.034768      1
8  orange  0.739888      1


    fruit  price
0   apple   11.0
1  banana    2.0
2  orange    5.0


In [ ]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

print(df1)
print("\n")
print(df2)
print("\n")
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])

    fruit  weight  price
0   apple    high      7
1  banana  medium      1
2  orange     low      4
3   apple    high      9
4  banana  medium     12
5  orange     low      3
6   apple    high     13
7  banana  medium      6
8  orange     low     10


   pazham  kilo  price
0   apple  high      1
1  orange   low      6
2    pine  high     14
3   apple   low     12
4  orange  high     14
5    pine   low      5




fruit weight  price_left  pazham  kilo  price_right
0   apple   high           7   apple  high            1
1   apple   high           9   apple  high            1
2   apple   high          13   apple  high            1
3  orange    low           4  orange   low            6
4  orange    low           3  orange   low            6
5  orange    low          10  orange   low            6

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

print(df)
print("\n")
df['a_lag1'] = df['a'].shift(-1)
df['b_lead1'] = df['b'].shift(1)
print(df)

    a   b   c   d
0  62  52  42  18
1  14  69  27  45
2   6  19  11  37
3  69  44  46  11
4  71  55  78  74


    a   b   c   d  a_lag1  b_lead1
0  62  52  42  18    14.0      NaN
1  14  69  27  45     6.0     52.0
2   6  19  11  37    69.0     69.0
3  69  44  46  11    71.0     19.0
4  71  55  78  74     NaN     44.0


In [ ]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

print(df)
print("\n")
pd.value_counts(df.values.ravel())

   a  b  c  d
0  7  7  3  6
1  3  9  2  3
2  4  2  6  1
3  8  3  1  7
4  6  4  8  2




3    4
7    3
6    3
2    3
4    2
1    2
8    2
9    1
dtype: int64

In [ ]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)
print("\n")
df_out = df.row.str.split(',|\t', expand=True)
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka


0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
